name: SMPCore
author: Cloudnode
version: '${project.version}'
main: pro.cloudnode.smp.smpcore.SMPCore
api-version: '1.20'
commands:
  smpcore:
    description: SMPCore Main command
    usage: /<command>
    aliases: [ smp ]
  ban:
    permission: smpcore.ban
    description: Ban a member and all of their alts
    usage: /<command> <username> [reason]
  unban:
    permission: smpcore.ban
    description: Unban a member and all of their alts
    usage: /<command> <username>
    aliases: [ pardon ]
  alts:
    permission: smpcore.alt
    description: Manage alternate accounts
    usage: /<command>
    aliases: [ alt ]
  seen:
    permission: smpcore.seen
    description: Check when a player was last online
    usage: /<command> <player>
    aliases: [ lastseen ]
  time:
    permission: smpcore.time
    description: See the current game time and date
    usage: /<command>
    aliases: [ date, today ]
  nation:
    permission: smpcore.nation
    description: Manage nations
    usage: /<command>
    aliases: [ nations, country, countries ]
